In [5]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [4]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [6]:
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
arr=np.ones((3,6))
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [8]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
arr=np.linspace(0,16,6)
print(arr)

[ 0.   3.2  6.4  9.6 12.8 16. ]


In [11]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [12]:
print(arr.ndim)

2


In [13]:
print(arr.size)

6


In [14]:
print(arr.dtype)

int64


In [15]:
arr=np.array([10,20,30,40])
print(arr[0])
print(arr[2])

10
30


In [16]:
print(arr[-1])

40


In [17]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0,1])
print(arr[1,2])

2
6


In [18]:
arr=np.array([10,20,30,40,50,60])
print(arr[1:4])

[20 30 40]


In [19]:
print(arr[:3])

[10 20 30]


In [20]:
print(arr[3:])

[40 50 60]


In [21]:
print(arr[::2])

[10 30 50]


In [22]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


In [23]:
arr=np.arange(1,13)
new_arr=arr.reshape(3,4)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
arr=np.arange(1,13)
new_arr=arr.reshape(2,2,3)
print(new_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [28]:
arr=np.array([[1,2],[3,4]])
print(arr.flatten())

[1 2 3 4]


In [2]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [3]:
print(a-b)

[-3 -3 -3]


In [5]:
print(a*b)
print(a/b)
print(b+a)
print(b-a)

[ 4 10 18]
[0.25 0.4  0.5 ]
[5 7 9]
[3 3 3]


In [6]:
print(a+10)
print(a*2)

[11 12 13]
[2 4 6]


In [7]:
arr=np.array([10,20,30,40,50])
print(np.sum(arr))

150


In [8]:
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

30.0
50
10


In [9]:
print(np.std(arr))

14.142135623730951
