In [6]:
#program 1
#create a numpy array of 10 integers and display shape size and datatype
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.shape)
print(arr.size)
print(arr.dtype)



(10,)
10
int64


In [16]:
#program 2
#create a 3 x 3 matrix and access first element , last element and entire second element
a=np.arange(1,10).reshape(3,3)
print(a)
first_element=a[0,0]
second_element=a[-1,-1]
second_row=a[1,:]
print("First_element:",first_element)
print("second_element:",second_element)
print("second_row:",second_row)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
First_element: 1
second_element: 9
second_row: [4 5 6]


In [15]:
#program 3
#create an array from 1 to 20 and display 1st 10 elements ,last 5 elements and alternative elements
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(a[:10])
print(a[14:])
print(a[::2])

[ 1  2  3  4  5  6  7  8  9 10]
[15 16 17 18 19 20]
[ 1  3  5  7  9 11 13 15 17 19]


In [17]:
#program 4
#create an array of 12 elements and reshape it into 3 x 4 and 2 x 6
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)
new_a=a.reshape(3,4)
print(new_a)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
new_a=a.reshape(2,6)
print(new_a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [2]:
#program 5
#perform addition,subraction,multiplication and division operations on to arrays
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
